apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike.name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.featureKeyFilePath .Values.featureKeyFile }}
  {{ fail "Both legacy(featureKeyFilePath) and new(featureKeyFile) are configured! Use only one!" }}
  {{- end }}

  {{- if and (or .Values.featureKeyFilePath .Values.featureKeyFile) (.Values.featureKeyFileBase64) }}
  {{ fail "Both featureKeyFilePath/featureKeyFile and featureKeyFileBase64 are configured! Use only one!" }}
  {{- end }}

  {{- if and (not .Values.featureKeyFile) (not .Values.featureKeyFilePath) (not .Values.featureKeyFileBase64) (not .Values.aerospikeFeatureKeyFilePath) }}
  {{ fail "feature key file not provided!" }}
  {{- end }}

  # Old config for feature key file
  {{- if (.Values.featureKeyFilePath) }}
  features.conf: {{ .Values.featureKeyFilePath | b64enc | quote }}
  {{- end }}

  # New config for feature key file
  {{- if (.Values.featureKeyFile) }}
  features.conf: {{ .Values.featureKeyFile | b64enc | quote }}
  {{- end }}

  # feature key file as base64 directly
  {{- if (.Values.featureKeyFileBase64) }}
  features.conf: {{ .Values.featureKeyFileBase64 | quote }}
  {{- end }}
