# ------------------------------------------------------------------------------
# Copyright 2012-2020 Aerospike, Inc.
#
# Portions may be licensed to Aerospike, Inc. under one or more contributor
# license agreements.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.
# ------------------------------------------------------------------------------

## Aerospike Statefulset definition.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "aerospike.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &AerospikeDeploymentLabels
    app: {{ template "aerospike.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "aerospike.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "aerospike.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.dbReplicas }}
  template:
    metadata:
      labels: *AerospikeDeploymentLabels
      annotations:
        {{- if .Values.autoRolloutConfig }}
        # TODO: Add an entry for secrets when used in future
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "aerospike.fullname" . }}{{ else }}{{ .Values.rbac.serviceAccountName }}{{ end }}
      {{- if eq .Values.antiAffinity "hard" }}
      affinity:
      {{- with .Values.affinity  }}
{{ toYaml . | indent 8 }}
      {{- end }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name }}
      {{- else if eq .Values.antiAffinity "soft" }}
      affinity:
      {{- with .Values.affinity  }}
{{ toYaml . | indent 8 }}
      {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: {{ .Values.antiAffinityWeight }}
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                  - key: release
                    operator: In
                    values:
                    - {{ .Release.Name }}
      {{- else}}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- if .Values.hostNetworking }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: aerospike
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.aerospikeClientPort | default 3000 }}
          name: aero-client
        - containerPort: {{ .Values.aerospikeHeartbeatPort | default 3002 }}
          name: aero-mesh
        - containerPort: {{ .Values.aerospikeFabricPort | default 3001 }}
          name: aero-fabric
        - containerPort: {{ .Values.aerospikeInfoPort | default 3003 }}
          name: aero-info
        # Do not stop node before migrations are complete
        lifecycle:
          {{- if .Values.security.enabled }}
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - "/etc/aerospike/aerospike.sh -h localhost -p {{ .Values.aerospikeClientPort | default 3000 }} -s 'true' -o 'post-start' -a {{ .Values.security.username }} -b {{ .Values.security.password }} -U aerospikeHelm -P aerospikeHelm"
          {{- end }}
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              {{- if .Values.security.enabled }}
              - "/etc/aerospike/aerospike.sh -h localhost -p {{ .Values.aerospikeClientPort | default 3000 }} -s 'true' -o 'pre-stop' -U aerospikeHelm -P aerospikeHelm"
              {{- else }}
              - "/etc/aerospike/aerospike.sh -h localhost -p {{ .Values.aerospikeClientPort | default 3000 }} -s 'false' -o 'pre-stop'"
              {{- end }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            {{- if .Values.security.enabled }}
            - "asinfo -h localhost -p {{ .Values.aerospikeClientPort | default 3000 }} -U {{ .Values.security.username }} -P {{ .Values.security.password }} -v build"
            {{- else }}
            - "asinfo -h localhost -p {{ .Values.aerospikeClientPort | default 3000 }} -v build"
            {{- end }}
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
              port: {{ .Values.aerospikeClientPort | default 3000 }}
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
        volumeMounts:
        - name: confdir
          mountPath: /etc/aerospike
        {{- range $pv := .Values.persistenceStorage }}
        {{- if $pv.enabled }}
        {{- if eq $pv.volumeMode "Filesystem"}}
        - name: {{ $pv.name | quote }}
          mountPath: {{ $pv.mountPath | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- range $lv := .Values.volumes }}
        - name: {{ $lv.name | quote }}
          mountPath: {{ $lv.mountPath | quote }}
        {{- end }}
        volumeDevices:
        {{- range $pv := .Values.persistenceStorage }}
        {{- if $pv.enabled }}
        {{- if eq $pv.volumeMode "Block"}}
        - name: {{ $pv.name | quote }}
          devicePath: {{ $pv.devicePath | quote }}
        {{- end }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NAMESPACE
          value: {{ .Values.aerospikeNamespace | default "test" | quote }}
        - name: REPL_FACTOR
          value: {{ .Values.aerospikeReplicationFactor | default "2" | quote }}
        - name: MEM_GB
          value: {{ .Values.aerospikeNamespaceMemoryGB | default "1" | quote }}
        - name: DEFAULT_TTL
          value: {{ .Values.aerospikeDefaultTTL | default "0" | quote }}
        - name: FEATURE_KEY_FILE
          value: {{ .Values.aerospikeFeatureKeyFilePath | default "" | quote }}
        - name: SERVICE_PORT
          value: {{ .Values.aerospikeClientPort | default 3000 | quote }}
        - name: HB_PORT
          value: {{ .Values.aerospikeHeartbeatPort | default 3002 | quote }}
        - name: FABRIC_PORT
          value: {{ .Values.aerospikeFabricPort | default 3001 | quote }}
        - name: INFO_PORT
          value: {{ .Values.aerospikeInfoPort | default 3003 | quote }}
        # Downward API:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      {{- if .Values.enableAerospikeMonitoring }}
      - name: aerospike-prometheus-exporter
        image: "{{ .Values.exporterImage.repository }}:{{ .Values.exporterImage.tag }}"
        args: ["aerospike-prometheus-exporter", "--config", "/etc/aerospike-prometheus-exporter/ape.toml"]
        ports:
        - containerPort: {{ .Values.exporter.agentBindPort | default 9145 }}
          name: exporter
        volumeMounts:
        - name: apeconfdir
          mountPath: /etc/aerospike-prometheus-exporter
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AS_HOST
          value: {{ .Values.exporter.asHost | default "localhost" | quote }}
        - name: AS_PORT
          value: {{ .Values.exporter.asPort | default 3000 | quote }}
        - name: AGENT_BIND_HOST
          value: {{ .Values.exporter.agentBindHost | default "" | quote }}
        - name: AGENT_BIND_PORT
          value: {{ .Values.exporter.agentBindPort | default 9145 | quote }}
        - name: AGENT_LOG_LEVEL
          value: {{ .Values.exporter.agentLogLevel | default "info" | quote }}
        - name: AGENT_TIMEOUT
          value: {{ .Values.exporter.agentTimeout | default 10 | quote }}
        - name: AGENT_TAGS
          value: {{ .Values.exporter.agentTags | default "" | quote }}
        - name: AGENT_UPDATE_INTERVAL
          value: {{ .Values.exporter.agentUpdateInterval | default 5 |quote }}
        - name: TICKER_INTERVAL
          value: {{ .Values.exporter.tickerInterval | default 5 | quote }}
        - name: TICKER_TIMEOUT
          value: {{ .Values.exporter.tickerTimeout | default 5 | quote }}
        - name: AS_AUTH_MODE
          value: {{ .Values.exporter.asAuthMode | default "" | quote }}
        - name: AS_AUTH_USER
          value: {{ .Values.exporter.asAuthUser | default "" | quote }}
        - name: AS_AUTH_PASSWORD
          value: {{ .Values.exporter.asAuthPassword | default "" | quote }}
      {{- end }}
      initContainers:
      - name: aerospike-init
        image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
        volumeMounts:
        - name: confdir
          mountPath: /etc/aerospike
        - name: initconfigs
          mountPath: /configs
        {{- if .Values.enableAerospikeMonitoring }}
        - name: apeconfdir
          mountPath: /etc/aerospike-prometheus-exporter
        {{- end }}
        env:    # Variables needed by peer-finder for discovery
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE
          value: {{ template "aerospike.fullname" . }}
        - name: SERVICE_DNS_DOMAIN
          value: {{ .Values.clusterServiceDnsDomain | default "cluster.local" | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "{{ .Release.Name }}-{{ .Chart.Name }}"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HB_PORT
          value: {{ .Values.aerospikeHeartbeatPort | default 3002 | quote }}
        - name: AUTO_GENERATE_NODE_IDS
          value: {{ .Values.autoGenerateNodeIds | default false | quote }}
        - name: PLATFORM
          value: {{ .Values.platform | quote }}
        - name: HOST_NETWORK
          value: {{ .Values.hostNetworking | default false | quote }}
        - name: ENABLE_NODE_PORT_SERVICES
          value: {{ .Values.enableNodePortServices | default false | quote }}
        - name: ENABLE_LOADBALANCER_SERVICES
          value: {{ .Values.enableLoadBalancerServices | default false | quote }}
        - name: ENABLE_EXT_IP_SERVICES
          value: {{ .Values.enableExternalIpServices | default false | quote }}
      volumes:
      {{- if .Values.enableAerospikeMonitoring }}
      - name: apeconfdir
        emptyDir: {}
      {{- end }}
      - name: confdir
        emptyDir: {}
      - name: initconfigs
        configMap:
          name: {{ .Release.Name }}-conf
      {{- range $lv := .Values.volumes }}
      - name: {{ $lv.name | quote }}
{{ toYaml $lv.template  | indent 8}}
      {{- end }}
  volumeClaimTemplates:
    {{- range $pv := .Values.persistenceStorage }}
    {{- if $pv.enabled }}
    - metadata:
        name: {{ $pv.name }}
        labels: *AerospikeDeploymentLabels
      spec:
        volumeMode: {{ $pv.volumeMode }}
        accessModes:
          - {{ $pv.accessMode | quote }}
      {{- if hasKey $pv "storageClass" }}
        storageClassName: {{ $pv.storageClass | quote }}
      {{- end }}
        resources:
          requests:
            storage: {{ $pv.size | quote }}
    {{- end }}
    {{- end }}
---
